import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

live_config_reload = true

[window]
decorations = "None"
padding = { x = 0, y = 0 }
dynamic_padding = false
dynamic_title = true
class = { instance = "alacritty", general = "alacritty" }
opacity = 0.9

[font]
normal = { family = "MQFonts"}
offset = { x = 1, y = 6 }
size = 14

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[colors.hints]
start = { foreground = "#000000", background = "#ff6600" }
end = { foreground = "#000000", background = "#ffff00" }

[hints]
enabled = [
  { regex = "(\\[[^]]*\\]\\(([^)]*)\\))|([^ ]+)|([^\\s]*[0-9]\\.[^\\s]*)|((?:https?://|git@|git://|ssh://|ftp://|file:///)\\S+)|(--- a/(\\S+))|(\\+\\+\\+ b/(\\S+))|(sha256:([0-9a-f]{64}))|((?:[.\\w\\-@~]+)?(?:/[.\\w\\-@]+)+)|(#[0-9a-fA-F]{6})|([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(Qm[0-9a-zA-Z]{44})|([0-9a-f]{7,40})|(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})|([A-f0-9:]+:+[A-f0-9:]+[%\\w\\d]+)|(0x[0-9a-fA-F]+)|([0-9]{4,})" , action = "Copy", binding = { key = "Space", mods = "Control|Shift" } }
]

[keyboard]
bindings = [
  { key = "Space", mods = "Control|Shift", action = "None" },
  { key = ";", mods = "Control", chars = "\u0002" },
  { key = "s", mods = "Control", chars = "\u0002s\r" },
  { key = "s", mods = "Control|Shift", chars = "\u0002ds\r" },
]
