[manager]
[[manager.prepend_keymap]]
on   = ["g", "i"]
run  = 'shell --block "lazygit -f $0"'
desc = "File history"

[[manager.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''', "yank" ]

[[manager.prepend_keymap]]
on = [ "g", "r" ]
desc = "Go to root"
run = '''
	shell 'ya emit cd "$(git rev-parse --show-toplevel)"'
'''
