- name: "ToolBar"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install waybar"
      become: true
      community.general.pacman: 
        name: "waybar"
        state: "present"
    
    - name: "Install grim for taking screenshots"
      become: true
      community.general.pacman: 
        name: "grim"
        state: "present"
    
    - name: "Install swappy as snapshop editor tool"
      become: true
      community.general.pacman: 
        name: "swappy"
        state: "present"
    
    - name: "Install slurp for partial screenshots with grim"
      become: true
      community.general.pacman: 
        name: "slurp"
        state: "present"
    
    - name: "Install pavucontrol for sound control"
      become: true
      community.general.pacman: 
        name: "pavucontrol"
        state: "present"
    
