
- name: "Configs"
  hosts: localhost
  connection: local
  tasks:
    - name: "Link hyprland's config"
      ansible.builtin.file:
        src: "$PWD/../../hypr"
        dest: "~/.config/hypr"
        state: "link"
        force: true
    
    - name: "Link waybar's config"
      ansible.builtin.file:
        src: "$PWD/../../waybar"
        dest: "~/.config/waybar"
        state: "link"
        force: true

    - name: "Link neovim's config"
      ansible.builtin.file:
        src: "$PWD/../../nvim"
        dest: "~/.config/nvim"
        state: "link"
        force: true
    
    - name: "Link fish's config"
      ansible.builtin.file:
        src: "$PWD/../../fish/{{ item }}"
        dest: "~/.config/fish/{{ item }}"
        state: "link"
        force: true
      loop: 
        - "completions"
        - "functions"
        - "config.fish"
    
    - name: "Link starship's config"
      ansible.builtin.file:
        src: "$PWD/../../starship.toml"
        dest: "~/.config/starship.toml"
        state: "link"
        force: true
    
    - name: "Link wezterm's config"
      ansible.builtin.file:
        src: "$PWD/../../wezterm.lua"
        dest: "~/.wezterm.lua"
        state: "link"
        force: true
    
    - name: "Link ranger's config"
      ansible.builtin.file:
        src: "$PWD/../../ranger.conf"
        dest: "~/.config/ranger/ranger.conf"
        state: "link"
        force: true

    - name: "Link zellij's config"
      ansible.builtin.file:
        src: "$PWD/../../zellij"
        dest: "~/.config/zellij"
        state: "link"
        force: true
    
