- name: "Fonts"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install vazir font"
      community.general.pacman: 
        executable: "yay"
        name: 
          - "vazir-code-fonts"
        state: "present"

    - name: "Install nerd fonts"
      ansible.builtin.command:
        cmd: "echo https://www.nerdfonts.com/font-downloads > Symbols Nerd Font | Symbols Only"

    - name: "Copy fonts"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "~/.local/share/fonts"
      with_fileglob:
        src: "$PWD/../../fonts/*"
