- name: "Fonts"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install vazir font"
      community.general.pacman: 
        executable: "yay"
        name: 
          - "vazir-code-fonts"
        state: "present"

    - name: "Install nerd fonts"
      community.general.pacman: 
        executable: "yay"
        name: 
          - "ttf-nerd-fonts-symbols-mono"
        state: "present"

    - name: "Copy fonts"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "~/.local/share/fonts"
      with_fileglob:
        src: "$PWD/../../fonts/*"

    - name: "Add alias fonts for alacritty"
      ansible.builtin.file:
        src: "$PWD/../../fontconfig"
        dest: "~/.config/fontconfig"
        state: "link"
        force: true
