- name: "Fonts"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install vazir font"
      ansible.builtin.command:
        cmd: "echo https://github.com/rastikerdar/vazir-code-font/releases"
    
    - name: "Install nerd fonts"
      ansible.builtin.command:
        cmd: "echo https://www.nerdfonts.com/font-downloads > Symbols Nerd Font | Symbols Only"

          # - name: "Link fonts"
          #   ansible.builtin.file:
          #     src: "$PWD/../../fonts"
          #     dest: "~/.local/share/fonts"
          #     state: "link"
          #     force: true
    
