- name: "Grant access to yay"
  hosts: localhost
  connection: local
  tasks:
    - name: "Grant access to pacman and yay to do whatever without root access"
      ansible.builtin.shell:
        cmd: 'echo "$USER ALL=(ALL) NOPASSWD:/usr/bin/yay,/usr/bin/pacman" > /tmp/110-grant-pacman-yay'

    - name: "Copy access file"
      become: true
      ansible.builtin.copy:
        src: '/tmp/110-grant-pacman-yay'
        dest: '/etc/sudoers.d/110-grant-pacman-yay'
