- name: "Login manager"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install sddm"
      become: true
      ignore_errors: true
      community.general.pacman: 
        name: "sddm"
        state: "present"

    - name: "Start sddm system-wide"
      become: true
      ignore_errors: true
      ansible.builtin.service:
        name: "sddm"
        state: "started"
        enabled: true

    - name: "Install qt5"
      become: true
      community.general.pacman:
        name: "qt5-base"
        state: "present"

    - name: "Install qt5-quickcontrols2"
      become: true
      community.general.pacman:
        name: "qt5-quickcontrols2"
        state: "present"

    - name: "Install qt5-svg"
      become: true
      community.general.pacman:
        name: "qt5-svg"
        state: "present"

    - name: "Install qt5-graphicaleffects"
      become: true
      community.general.pacman:
        name: "qt5-graphicaleffects"
        state: "present"

    - name: "Install sddm theme"
      become: true
      community.general.pacman:
        name: "qt5-svg"
        state: "present"

    - name: "Clone theme"
      become: true
      ansible.builtin.git:
        repo: "https://github.com/MarianArlt/sddm-sugar-dark"
        dest: "/usr/share/sddm/themes/sugar-dark"
        depth: 1
        single_branch: true
        recursive: true
        version: master

    - name: "Add theme config"
      become: true
      ansible.builtin.file:
        src: "$PWD/../../sddm/theme/theme.conf"
        dest: "/usr/share/sddm/themes/sugar-dark/theme.conf"
        state: "link"
        force: true

    - name: "Enable theme"
      become: true
      ansible.builtin.file:
        src: "$PWD/../../sddm/config"
        dest: "/etc/sddm.conf.d"
        state: "hard"
        force: true
