- name: "Rofi"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install rofi"
      become: true
      community.general.pacman: 
        name: "rofi"
        state: "present"
    
    - name: "Clone themes"
      ansible.builtin.git:
        repo: "https://github.com/adi1090x/rofi.git"
        dest: "/tmp/rofi"
        depth: 1
        single_branch: true
        recursive: true
        version: master
    
    - name: "Permission the executable"
      ansible.builtin.file:
        path: "/tmp/rofi/setup.sh"
        mode: "0544"
    
    - name: "Install themes"
      ansible.builtin.command:
        chdir: "/tmp/rofi"
        cmd: "./setup.sh"
    
    - name: "Remove themes clone"
      ansible.builtin.file:
        path: "/tmp/rofi"
        state: "absent"
    
