- name: "Scripts"
  hosts: localhost
  connection: local
  tasks:
    - name: "Link scripts"
      ansible.builtin.file:
        src: "$PWD/../../scripts"
        dest: "~/.local/bin"
        state: "link"
        force: true

    - name: "Create wallpaper directory"
      ansible.builtin.file:
        path: "~/Pictures/wallpapers"
        state: "directory"
        mode: "0755"
        recurse: true

    - name: "Enable lockscreen cron"
      ansible.builtin.cron:
        name: "bing-lockscreen"
        job: "bing-wallpaper"
        minute: "0"

    - name: "Enable mirrorlist cron"
      become: true
      ansible.builtin.cron:
        name: "update-mirrorlist"
        job: "reflector --latest 30 --sort score --save /etc/pacman.d/mirrorlist"
        minute: "0"
        hour: "*/6"
