- name: "Services"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install gdm"
      become: true
      ignore_errors: true
      community.general.pacman: 
        name: "gdm"
        state: "present"
    
    - name: "Start gdm system-wide"
      become: true
      ignore_errors: true
      ansible.builtin.service:
        name: "gdm"
        state: "started"
        enabled: true

    - name: "Install cronie"
      become: true
      community.general.pacman: 
        name: "cronie"
        state: "present"
    
    - name: "Start cronie system-wide"
      become: true
      ansible.builtin.service:
        name: "cronie"
        state: "started"
        enabled: true

    - name: "Install gnome-keyring"
      become: true
      community.general.pacman: 
        name: "gnome-keyring"
        state: "present"

    - name: "Install archlinux-keyring"
      become: true
      community.general.pacman: 
        name: "archlinux-keyring"
        state: "present"
    
    - name: "Link services"
      ansible.builtin.file:
        src: "$PWD/../../services/{{ item }}"
        dest: "~/.config/systemd/user/{{ item }}"
        state: "link"
        force: true
      loop:
        - gnome-keyring-daemon.service
        - default.target.wants
        - sockets.target.wants
    
    - name: "Reload service"
      ansible.builtin.systemd_service:
        scope: "user"
        daemon_reload: true
    
    - name: "Start gnome-keyring service"
      ansible.builtin.service:
        name: "gnome-keyring-daemon"
        scope: "user"
        state: "started"
        enabled: true
