- name: "TUI"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install fish"
      become: true
      community.general.pacman: 
        name: "fish"
        state: "present"

    - name: "Install starship"
      become: true
      community.general.pacman: 
        name: "starship"
        state: "present"

    - name: "Install kitty"
      become: true
      community.general.pacman: 
        name: "kitty"
        state: "present"

    - name: "Install alacritty"
      become: true
      community.general.pacman: 
        name: "alacritty"
        state: "present"

    - name: "Install ranger"
      community.general.pacman: 
        executable: "yay"
        name: 
          - "ranger"
          - "python-pynvim"
        state: "present"

    - name: "Install zellij"
      become: true
      community.general.pacman: 
        name: "zellij"
        state: "present"

    - name: "Install xdotool for using sessions script"
      become: true
      community.general.pacman: 
        name: "xdotool"
        state: "present"

    - name: "Install eza in place of ls"
      become: true
      community.general.pacman: 
        executable: "yay"
        name: "eza"
        state: "present"

    - name: "Install zoxide in place of cd"
      become: true
      community.general.pacman: 
        executable: "yay"
        name: "zoxide"
        state: "present"

