- name: "Utilities"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install qalculate"
      community.general.pacman: 
        executable: "yay"
        name: "qalculate-gtk"
        state: "present"

    - name: "Install brave"
      community.general.pacman: 
        executable: "yay"
        name: "brave-bin"
        state: "present"

    - name: "Install heynote"
      community.general.pacman: 
        executable: "yay"
        name: "heynote"
        state: "present"
