- name: "Utilities"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install calculator"
      community.general.pacman: 
        executable: "yay"
        name: "qalculate-gtk"
        state: "present"

    - name: "Install browser"
      community.general.pacman: 
        executable: "yay"
        name: "brave"
        state: "present"

    - name: "Install musicplayer"
      community.general.pacman: 
        executable: "yay"
        name: "tauon-music-box"
        state: "present"

