- name: "Utilities"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install qalculate"
      community.general.pacman: 
        executable: "yay"
        name: "qalculate-gtk"
        state: "present"

    - name: "Install vivaldi"
      community.general.pacman: 
        executable: "yay"
        name: "vivaldi"
        state: "present"

    - name: "Install vivaldi codecs"
      community.general.pacman: 
        executable: "yay"
        name: "vivaldi-ffmpeg-codecs"
        state: "present"

    - name: "Install heynote"
      community.general.pacman: 
        executable: "yay"
        name: "heynote"
        state: "present"
