#!/bin/bash
project_name="$(basename "$(realpath "$(git rev-parse --git-common-dir --path-format=absolute)" | sed "s#/.git\$##")")"
current_branch_name="$(echo "$1" | sed "s#/#-#g")"
name="$project_name"__"$current_branch_name"

git worktree add -q "../$name" "$1"

cp ./docker-compose.dev.yml ../$name/
cp ./src/.env ../$name/src/
echo "CONTAINER_NAME=$name" > ../$name/.env

# For Golang projects, generate sqlc files
if [[ -f src/go.mod ]]; then
    sh -c "cd \"../$name/src\" && go tool sqlc generate"
fi

# For PHP projects
if [[ -f src/composer.json ]]; then
    cp nginx.conf "../$name/nginx.conf"
    sed -i "s/fastcgi_pass .*$/fastcgi_pass ${name}_app:9000;/" "../$name/nginx.conf"
fi

sh -c "cd \"../$name\" && docker compose -f docker-compose.dev.yml up -d"

sessions "$PWD/../$name"
