#!/bin/bash

# $1 is the main branch directory
# $2 is the new/exsiting branch name for creating a new worktree

MAIN_BRANCH_DIR="$1"
cd "$MAIN_BRANCH_DIR"

if [[ -z "$2" ]]; then
    current_branch_name=$(git branch -a | sed 's#remotes/origin/##' | tr -d ' ' | grep -v '\(HEAD\|*\)' | fzf --print-query --prompt "Branch > " --header "Select branch")
    if [[ -z "$current_branch_name" ]]; then
        exit 1
    fi
else
    current_branch_name="$2"
fi

current_branch_name=$(echo $current_branch_name | tr -d " ")
current_dir_name="$(echo "$current_branch_name" | sed "s#/#-#g")"
project_name="$(basename "$(realpath "$(git rev-parse --git-common-dir --path-format=absolute)" | sed "s#/.git\$##")")"
CONTAINER_NAME="$project_name"__"$current_dir_name"
NEW_BRANCH_DIR="$MAIN_BRANCH_DIR/../$CONTAINER_NAME"

# Create branch if it doesn't exist
if [[ -z "$(git rev-parse --verify --quiet "$current_branch_name")" ]]; then
    echo "Creating branch $current_branch_name..."
    git branch "$current_branch_name"
fi

echo "Adding worktree $current_branch_name..."
git worktree add -q "$NEW_BRANCH_DIR" "$current_branch_name"

echo "Copying files..."
cp "$MAIN_BRANCH_DIR/docker-compose.dev.yml" "$NEW_BRANCH_DIR/docker-compose.dev.yml"
cp "$MAIN_BRANCH_DIR/src/.env" "$NEW_BRANCH_DIR/src/.env"

echo "Creating .envrc file..."
cp "$MAIN_BRANCH_DIR/.envrc" "$NEW_BRANCH_DIR/.envrc"
sed -i "s/^export CONTAINER_NAME=.*$/export CONTAINER_NAME=$CONTAINER_NAME/" "$NEW_BRANCH_DIR/.envrc"

# For Golang projects, generate sqlc files
if [[ -f src/go.mod ]]; then
    echo "Generating sqlc files..."
    sh -c "cd \"$NEW_BRANCH_DIR/src\" && go tool sqlc generate"
fi

# For PHP projects
if [[ -f src/composer.json ]]; then
    echo "Copying nginx.conf..."
    cp nginx.conf "$NEW_BRANCH_DIR/nginx.conf"
    sed -i "s/fastcgi_pass .*$/fastcgi_pass ${CONTAINER_NAME}:9000;/" "$NEW_BRANCH_DIR/nginx.conf"
fi

echo "Starting containers..."
cd "$NEW_BRANCH_DIR"
eval "$(direnv export bash)"
docker compose -f docker-compose.dev.yml up -d

echo "Create session..."
sessions "$NEW_BRANCH_DIR"
