#!/bin/bash

# $1 is the main branch directory
# $2 is the new/exsiting branch name for creating a new worktree

project_name="$(basename "$(realpath "$(git rev-parse --git-common-dir --path-format=absolute)" | sed "s#/.git\$##")")"
current_branch_name="$(echo "$2" | sed "s#/#-#g")"
name="$project_name"__"$current_branch_name"

eval "$(direnv export bash)"

cd "../$name" && docker compose -f docker-compose.dev.yml down

tmux kill-session -t "$name"

git worktree remove "../$name"
