#!/usr/bin/env bash
if [ "$(command -v xdotool)" = "" ]; then
    echo "xdotool is not installed"
    exit 1
fi

if [ "$(command -v zellij)" = "" ]; then
    echo "Zellij is not installed"
    exit 1
fi

if [ "$(command -v zoxide)" = "" ]; then
    echo "Zoxide is not installed"
    exit 1
fi

# If we're inside of zellij, detach
if [[ -n $ZELLIJ ]]; then
	xdotool key Ctrl+b d
	xdotool type $(basename $0) && xdotool key Enter
	exit
fi

home_replacer() {
    HOME_REPLACER=""                                          # default to a noop
    echo "$HOME" | grep -E "^[a-zA-Z0-9\-_/.@]+$" &>/dev/null # chars safe to use in sed
    HOME_SED_SAFE=$?
    if [ $HOME_SED_SAFE -eq 0 ]; then # $HOME should be safe to use in sed
        HOME_REPLACER="s|^$HOME/|~/|"
    fi
    echo "$HOME_REPLACER"
}

transform_home_path() {
    HOME_SED_SAFE=$?
    if [ $HOME_SED_SAFE -eq 0 ]; then
        echo "$1" | sed -e "s|^~/|$HOME/|"
    else
        echo "$1"
    fi
}

set_user_var() {
   printf "\033]1337;SetUserVar=%s=%s\007" $1 `echo -n $2 | base64`
}

fzf_window() {
	fzf --reverse --no-sort --border "rounded" --info inline --pointer "→" --prompt "Session > " --header "Select session" --preview "echo {2} | grep -q 'Session' && echo {} || ls {3}"
}

select_project() {
    project_dir=$({ zellij list-sessions -s | awk '{ print "("NR") [Session]\t"$1 }'; zoxide query -l | awk '{ print "("NR") [Directory]\t"$1 }' ; } | fzf_window)
    if [ "$project_dir" = "" ]; then
        exit
    fi
	echo "$project_dir"
}

is_selected_session(){
	if [ -n "$(echo "$1" | grep "^([0-9]*) \[Session\]")" ]; then
		echo 1
	fi
}

get_sanitized_selected(){
	echo "$1" | sed "s/^([0-9]*) \[[^]]*\]//"
}

get_session_name() {
    project_dir=$1
    directory=$(basename "$project_dir")
    session_name=$(echo "$directory" | tr ' .:' '_')
    echo "$session_name"
}

selected=$(select_project)
if [ -z "$selected" ]; then
	exit 0
fi

is_session=$(is_selected_session "$selected")
selected_name=$(get_sanitized_selected "$selected")
if [ -z "$is_session" ]; then
	session_name=$(get_session_name "$(transform_home_path "$selected_name")")
	session=$(zellij list-sessions | grep "$session_name")
	set_user_var ZELLIJ 1
	zellij attach $session_name -c options --default-cwd $selected_name
else
	set_user_var ZELLIJ 1
	zellij attach $selected_name -c
fi
