#!/usr/bin/bash
if [ "$(command -v tmux)" = "" ]; then
    echo "Tmux is not installed"
    exit 1
fi


LAST_SESSION="$([[ -f /tmp/zellij_last_session ]] && cat /tmp/zellij_last_session)"

fzf_window() {
    fzf --reverse \
        --border "rounded" \
        --info inline \
        --delimiter='\t' \
        --pointer "→" \
        --with-nth=1,2,3 \
        --prompt "Session > " \
        --header "Select session" \
        --preview "bash -c \"echo {2} | grep -q 'Session' && echo {} || ls {4}\"" \
        --bind "ctrl-a:become(gwa {4} 1>&2)" \
        --bind "ctrl-x:execute(sessions {4} gwr)"
}

set_last_session() {
    echo "$1" > /tmp/zellij_last_session
}

last_session() {
    if [[ -n "$LAST_SESSION" ]]; then
        echo $LAST_SESSION | awk 'function basename(file) {sub(".*/", "", file); return file} {print "("NR")\t[Recent]\t" basename($1) "\t" $1 }'
    fi
}

sessions_list_names() {
    tmux list-sessions -F '#{session_attached} #S #{@root}'
}

sessions_list(){
    if [[ -n "$LAST_SESSION" ]]; then
        sessions_list_names | grep -xv ".*\s$(echo $LAST_SESSION)$" | awk '{ print "("NR")\t[Session]\t"$2 "\t" $3 }'
    else
        sessions_list_names | awk '{ print "("NR")\t[Session]\t"$ "\t" $3 }'
    fi
}

project_list(){
    project_list_session_excluded | tr --truncate-set1 " /" "\n" | awk 'function basename(file) {sub(".*/", "", file); return file} {print "("NR")\t[Directory]\t" basename($1) "\t" $1 }'
}

project_list_session_excluded(){
    list=$(find /mnt/Projects/ -maxdepth 1 -type d)
    list=$(echo -e "$(realpath ~/dotfiles)\n${list}")
    OLDIFS="$IFS"
    IFS=$'\n'
    bar=$(sessions_list_names | awk '{print $3}')
    for item in $list; do
        for b in $bar; do
            if [[ "$item" == "$b" ]]; then
                continue 2
            fi
        done
        echo $item
    done
    IFS="$OLDIFS"
}

select_project() {
    project_dir=$({ last_session; sessions_list; project_list; } | fzf_window)
    if [ "$project_dir" = "" ]; then
        exit
    fi
    echo "$project_dir"
}

get_name_selected(){
    basename "$1"
}

get_cwd_selected(){
    echo "$1" | awk '{print $4}'
}

if [[ -n "$1" ]]; then
    selected=$(realpath $1)
else
    selected=$(select_project)
    selected=$(get_cwd_selected "$selected")
fi

if [ -z "$selected" ]; then
    exit 0
fi

if [[ "$#" -eq 2 ]]; then
    if [[ "$2" == "gwr" ]]; then
        name=$(basename $1)
        sh -c "
            cd '$1' && docker compose -f docker-compose.dev.yml down &&
            git worktree remove '$1' &&
            tmux kill-session -t '$name'
        "
        exit 0
    fi

    echo "Action '$2' not supported"
    exit 1
fi

session_name=$(get_name_selected "$selected")
session=$(tmux has-session -t="$session_name" 2> /dev/null)
current_session=$(sessions_list_names | grep '^1 ' | awk '{print $2}')

set_last_session "$selected"

if ! tmux has-session -t=$session_name 2> /dev/null; then
    tmux new-session -ds $session_name -c "$selected"
    tmux set-option -t $session_name @root "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $session_name
else
    tmux switch-client -t $session_name
fi
