#!/bin/bash

STATE_FILE="/tmp/hyprland-touchpad-mode.status"

# Last state
if [[ -f "$STATE_FILE" ]]; then
  LAST_MODE=$(cat "$STATE_FILE")
else
  LAST_MODE="0"
fi

# Next mode
case "$LAST_MODE" in
  "false") NEXT_MODE="true"; STATUS="Enabled" ;;
  *) NEXT_MODE="false"; STATUS="Disabled" ;;
esac

touchpads=$(hyprctl devices -j | jq -r '.mice | .[] | select(.name | test("touch")) | .name')

if [[ -z "$touchpads" ]]; then
  notify-send "No touchpads found"
  exit 1
fi

for touchpad in $touchpads; do
    hyprctl eval "hl.device({ name = '$touchpad', enabled = $NEXT_MODE })"
done

notify-send "Touchpad mode: $STATUS"
echo "$NEXT_MODE" > "$STATE_FILE"
