- name: "Install bitwarden"
  become: true
  community.general.pacman: 
    name: ["bitwarden-cli"]
    state: "present"
  tags:
    - install
    - bitwarden

- name: "Install wtype for bitwarden script"
  become: true
  community.general.pacman: 
    name: "wtype"
    state: "present"
  tags:
    - install
    - bitwarden
