- name: "Install vazir font"
  kewlfft.aur.aur:
    use: "yay"
    name: 
      - "vazir-code-fonts"
    state: "present"
  tags:
    - install
    - fonts

- name: "Install nerd fonts"
  kewlfft.aur.aur:
    use: "yay"
    name: 
      - "ttf-nerd-fonts-symbols-mono"
    state: "present"
  tags:
    - install
    - fonts

- name: Display dotfiles fonts
  ansible.builtin.debug: msg={{ lookup('ansible.builtin.fileglob', '../fonts/*') }}
  tags:
    - install
    - config
    - fonts

- name: "Copy fonts"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.local/share/fonts"
  with_fileglob:
    - "../fonts/*"
  tags:
    - install
    - config
    - fonts
