- name: "Install sddm"
  become: true
  ignore_errors: true
  community.general.pacman: 
    name: "sddm"
    state: "present"
  tags:
    - install

- name: "Install sddm requirements"
  become: true
  community.general.pacman:
    name: ["qt5-base",  "qt5-quickcontrols2",  "qt5-svg",  "qt5-graphicaleffects",  "qt5-svg"]
    state: "present"
  tags:
    - install

- name: "Purge sddm old theme"
  become: true
  ansible.builtin.file:
    path: "/usr/share/sddm/themes/sugar-dark"
    state: "absent"
  tags:
    - install
    - config

- name: "Clone sddm theme"
  become: true
  ansible.builtin.git:
    repo: "https://github.com/MarianArlt/sddm-sugar-dark"
    dest: "/usr/share/sddm/themes/sugar-dark"
    depth: 1
    single_branch: true
    recursive: true
    version: master
  tags:
    - install
    - config

- name: "Add sddm theme config"
  become: true
  ansible.builtin.file:
    src: "$PWD/sddm/theme/theme.conf"
    dest: "/usr/share/sddm/themes/sugar-dark/theme.conf"
    state: "hard"
    force: true
  tags:
    - install
    - config

- name: "Purge sddm old config"
  become: true
  ansible.builtin.file:
    path: "/etc/sddm.conf.d"
    state: "absent"
  tags:
    - install
    - config
    - sddm

- name: "Enable sddm theme"
  become: true
  ansible.builtin.file:
    src: "$PWD/sddm/config"
    dest: "/etc/sddm.conf.d"
    state: "link"
    force: true
  tags:
    - install
    - config
    - sddm

- name: "Start sddm system-wide"
  become: true
  ignore_errors: true
  ansible.builtin.service:
    name: "sddm"
    state: "started"
    enabled: true
  tags:
    - install

