- name: "Link scripts"
  ansible.builtin.file:
    src: "$PWD/scripts"
    dest: "~/.local/bin"
    state: "link"
    force: true
  tags:
    - install
    - config

- name: "Create wallpaper directory"
  ansible.builtin.file:
    path: "~/Pictures/wallpapers"
    state: "directory"
    mode: "0755"
    recurse: true
  tags:
    - install
    - config

- name: "Enable lockscreen cron"
  ansible.builtin.cron:
    name: "bing-lockscreen"
    job: "~/.local/bin/./bing-wallpaper"
    minute: "0"
  tags:
    - install
    - config

- name: "Enable mirrorlist cron"
  become: true
  ansible.builtin.cron:
    name: "update-mirrorlist"
    job: "reflector --latest 30 --sort score --save /etc/pacman.d/mirrorlist"
    minute: "0"
    hour: "*/6"
  tags:
    - install
    - config
