- name: "Install cronie"
  become: true
  community.general.pacman: 
    name: "cronie"
    state: "present"
  tags:
    - install
    - services

- name: "Start cronie system-wide"
  become: true
  ansible.builtin.service:
    name: "cronie"
    state: "started"
    enabled: true
  tags:
    - install
    - services

- name: "Start pipewire-pulse"
  ansible.builtin.service:
    name: pipewire-pulse
    state: "started"
    enabled: true
  tags:
    - install
    - services

- name: "Start pipewire-media-session"
  ansible.builtin.service:
    name: "pipewire-media-session"
    state: "started"
    enabled: true
  tags:
    - install
    - services

- name: "Install gnome-keyring"
  become: true
  community.general.pacman: 
    name: "gnome-keyring"
    state: "present"
  tags:
    - install
    - services

- name: "Install archlinux-keyring"
  become: true
  community.general.pacman: 
    name: "archlinux-keyring"
    state: "present"
  tags:
    - install
    - services

- name: "Link services"
  ansible.builtin.file:
    src: "$PWD/services/{{ item }}"
    dest: "~/.config/systemd/user/{{ item }}"
    state: "link"
    force: true
  loop:
    - gnome-keyring-daemon.service
    - default.target.wants
    - sockets.target.wants
  tags:
    - install
    - services

- name: "Reload service"
  ansible.builtin.systemd_service:
    scope: "user"
    daemon_reload: true
  tags:
    - install
    - services

- name: "Start gnome-keyring service"
  ansible.builtin.service:
    name: "gnome-keyring-daemon"
    scope: "user"
    state: "started"
    enabled: true
  tags:
    - install
    - services
