- name: "Install shell"
  become: true
  community.general.pacman: 
    name: ["fish", "nushell"]
    state: "present"
  tags:
    - install

- name: "Install starship"
  become: true
  community.general.pacman: 
    name: "starship"
    state: "present"
  tags:
    - install

- name: "Install filemanager"
  community.general.pacman: 
    executable: "yay"
    name: 
      - "yazi"
    state: "present"
  tags:
    - install

- name: "Install zellij"
  become: true
  community.general.pacman: 
    name: "zellij"
    state: "present"
  tags:
    - install

- name: "Install wtype for bitwarden script"
  become: true
  community.general.pacman: 
    name: "wtype"
    state: "present"
  tags:
    - install

- name: "Install eza in place of ls"
  become: true
  community.general.pacman: 
    executable: "yay"
    name: "eza"
    state: "present"
  tags:
    - install

- name: "Install zoxide in place of cd"
  become: true
  community.general.pacman: 
    executable: "yay"
    name: "zoxide"
    state: "present"
  tags:
    - install

- name: "Install xcp - cp alternative"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: "xcp"
    state: "present"
  tags:
    - install

- name: "Install dust - du alternative"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: "dust"
    state: "present"
  tags:
    - install

- name: "Install lazygit"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: "lazygit"
    state: "present"
  tags:
    - install

- name: "Install difftastic in place of diff"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: "difftastic"
    state: "present"
  tags:
    - install
