- name: "Install waybar"
  become: true
  community.general.pacman: 
    name: "waybar"
    state: "present"
  tags:
    - install
    - waybar

- name: "Install grim for taking screenshots"
  become: true
  community.general.pacman: 
    name: "grim"
    state: "present"
  tags:
    - install
    - waybar

- name: "Install swappy as snapshop editor tool"
  become: true
  community.general.pacman: 
    name: "swappy"
    state: "present"
  tags:
    - install
    - waybar

- name: "Install slurp for partial screenshots with grim"
  become: true
  community.general.pacman: 
    name: "slurp"
    state: "present"
  tags:
    - install
    - waybar

- name: "Install pavucontrol for sound control"
  become: true
  community.general.pacman: 
    name: "pavucontrol"
    state: "present"
  tags:
    - install
    - waybar

- name: "Install icons"
  become: true
  community.general.pacman: 
    name: "kiconthemes"
    state: "present"
  tags:
    - install
    - waybar

- name: "Remove waybar's old config"
  ignore_errors: true
  ansible.builtin.file:
    path: "~/.config/waybar"
    state: "absent"
  tags:
    - install
    - config
    - waybar

- name: "Link waybar's config"
  ansible.builtin.file:
    src: "$PWD/waybar"
    dest: "~/.config/waybar"
    state: "link"
    force: true
  tags:
    - install
    - config
    - waybar
