- name: "Install hyprland"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: ["hyprland", "hyprpicker-git", "hyprsunset"]
    state: "present"
  tags:
    - install

- name: "Install wl-clipboard"
  become: true
  community.general.pacman: 
    name: "wl-clipboard"
    state: "present"
  tags:
    - install

- name: "Install cliphist"
  become: true
  community.general.pacman: 
    name: "cliphist"
    state: "present"
  tags:
    - install

- name: "Install highlight"
  become: true
  community.general.pacman: 
    name: "highlight"
    state: "present"
  tags:
    - install

- name: "Install swayidle"
  become: true
  community.general.pacman: 
    name: "swayidle"
    state: "present"
  tags:
    - install

- name: "Install xdg-desktop-portal-hyprland"
  become: true
  community.general.pacman: 
    name: [ "xdg-desktop-portal-wlr", "xdg-desktop-portal-hyprland",  "xdg-desktop-portal-gtk"]
    state: "present"
  tags:
    - install

- name: "Install piprwire"
  become: true
  community.general.pacman: 
    name: ["pipewire",  "pipewire-pulse",  "pipewire-media-session"]
    state: "present"
  tags:
    - install

- name: "Install waypaper"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: "waypaper-git"
    state: "present"
  tags:
    - install

- name: "Install swaylock-effects"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: "swaylock-effects-git"
    state: "present"
  tags:
    - install

- name: "Install swww"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: "swww"
    state: "present"
  tags:
    - install

- name: "Install notification daemon"
  ignore_errors: true
  community.general.pacman: 
    executable: "yay"
    name: ["swaync", "avizo", "pamixer", "brightnessctl"]
    state: "present"
  tags:
    - install

- name: "Install udiskie for automounting removable devices"
  ignore_errors: true
  community.general.pacman: 
    name: "udiskie"
    state: "present"
  tags:
    - install

