- name: "Install highlight"
  become: true
  community.general.pacman: 
    name: "highlight"
    state: "present"
  tags:
    - install
    - wm

- name: "Install audio driver"
  become: true
  community.general.pacman: 
    name: ["pipewire", "pipewire-pulse", "wireplumber"]
    state: "present"
  tags:
    - install
    - wm

- name: "Install waypaper"
  ignore_errors: true
  kewlfft.aur.aur:
    use: "yay"
    name: ["awww", "waypaper-git", "python-imageio", "python-screeninfo"]
    state: "present"
  tags:
    - install
    - wm

- name: "Install notification daemon"
  ignore_errors: true
  kewlfft.aur.aur:
    use: "yay"
    name: ["swaync", "avizo", "pamixer", "brightnessctl"]
    state: "present"
  tags:
    - install
    - wm

- name: "Remove swaync's old config"
  ignore_errors: true
  ansible.builtin.file:
    path: "~/.config/swaync"
    state: "absent"
  tags:
    - install
    - config
    - wm

- name: "Link swaync's config"
  ansible.builtin.file:
    src: "$PWD/swaync"
    dest: "~/.config/swaync"
    state: "link"
    force: true
  tags:
    - install
    - config
    - wm

- name: "Install udiskie for automounting removable devices"
  ignore_errors: true
  community.general.pacman: 
    name: "udiskie"
    state: "present"
  tags:
    - install
    - wm

